// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_82d2sdQ5xYbv47Xtjuf_xEMOCIUMR2k',
    appId: '1:143091808279:web:aadea995292ff635c6c452',
    messagingSenderId: '143091808279',
    projectId: 'modul4-2eebd',
    authDomain: 'modul4-2eebd.firebaseapp.com',
    storageBucket: 'modul4-2eebd.appspot.com',
    measurementId: 'G-5P8ZLNS394',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfopbWJrJJJJ1UeTa8r54VwpPNzr7GTM',
    appId: '1:143091808279:android:229f3a475023106dc6c452',
    messagingSenderId: '143091808279',
    projectId: 'modul4-2eebd',
    storageBucket: 'modul4-2eebd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUoLgJjXePUcy7cckn2H-PlNZEUeI3vlQ',
    appId: '1:143091808279:ios:328d8f6b348e99ffc6c452',
    messagingSenderId: '143091808279',
    projectId: 'modul4-2eebd',
    storageBucket: 'modul4-2eebd.appspot.com',
    iosBundleId: 'com.example.petHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUoLgJjXePUcy7cckn2H-PlNZEUeI3vlQ',
    appId: '1:143091808279:ios:40e7cd0107191bacc6c452',
    messagingSenderId: '143091808279',
    projectId: 'modul4-2eebd',
    storageBucket: 'modul4-2eebd.appspot.com',
    iosBundleId: 'com.example.petHealth.RunnerTests',
  );
}
