// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhLCzW39d5ThMh6_Xvd9YmQd34c69OoTU',
    appId: '1:774563097068:web:caeb1a5b0d553ce29ef8c9',
    messagingSenderId: '774563097068',
    projectId: 'modul4mobile-598a1',
    authDomain: 'modul4mobile-598a1.firebaseapp.com',
    storageBucket: 'modul4mobile-598a1.appspot.com',
    measurementId: 'G-V1YKSMHP62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzAB-G0iawNsKeLb-aXl7uogfOqxkuMtE',
    appId: '1:774563097068:android:14de687a3af0bf239ef8c9',
    messagingSenderId: '774563097068',
    projectId: 'modul4mobile-598a1',
    storageBucket: 'modul4mobile-598a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8LKnQvzGG-isalxt6zTxuuQhoD-4iBY',
    appId: '1:774563097068:ios:24d5b72926bdeb409ef8c9',
    messagingSenderId: '774563097068',
    projectId: 'modul4mobile-598a1',
    storageBucket: 'modul4mobile-598a1.appspot.com',
    iosBundleId: 'com.example.petHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_8LKnQvzGG-isalxt6zTxuuQhoD-4iBY',
    appId: '1:774563097068:ios:8a5dcfaccdffafcf9ef8c9',
    messagingSenderId: '774563097068',
    projectId: 'modul4mobile-598a1',
    storageBucket: 'modul4mobile-598a1.appspot.com',
    iosBundleId: 'com.example.petHealth.RunnerTests',
  );
}
